name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Define version like 0.0.2 or 1.0.0'
        required: true
      version_code:
        description: 'Define version code 10, 20, 30, etc'
        required: true
      desktop_version:
        description: 'Define desktop version like 1.0.0 or higher'
        required: false
        default: '1.0.0'

env:
  VERSION: ${{ github.event.inputs.version }}
  DESKTOP_VERSION: ${{ github.event.inputs.desktop_version }}
  VERSION_CODE: ${{ github.event.inputs.version_code }}
  IS_DEBUG: ${{ vars.IS_DEBUG }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  SENTRY_ENVIRONMENT: ${{ vars.SENTRY_ENVIRONMENT }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

concurrency:
  group: create-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-checks:
    runs-on: macos-latest
    environment: production
    steps:

      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configure signing keys
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: |
          mkdir release;
          echo $KEYSTORE | base64 -d > release/release.jks;
      - name: Run DB Checks
        run: |
          ./gradlew generateCommonMainNinjaDatabaseSchema;
          ./gradlew verifySqlDelightMigration;

      - name: Build Release
        run: ./gradlew :androidApp:bundleRelease :androidApp:assembleRelease

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Signed Builds
          path: |
            androidApp/build/outputs/bundle/release/androidApp-release.aab
            androidApp/build/outputs/apk/release/androidApp-release.apk
            androidApp/build/outputs/mapping/release/mapping.txt

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ SERVICE_ACCOUNT_JSON }}
          packageName: dev.example.MyApp
          releaseFiles:  androidApp/build/outputs/bundle/release/androidApp-release.aab
          track: alpha
          status: draft
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew
          mappingFile: androidApp/build/outputs/mapping/release/mapping.txt
            
        
