name: PR Check
on:
  pull_request:
    branches: [ main ]

concurrency:
  group: pr-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Branch
        uses: actions/checkout@v1

      - name: Set up JDK 17
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '17'

      - name: Run Spotless
        run: ./gradlew spotlessCheck

      - name: Run Lint
        run: ./gradlew lint

      - name: Run DB Checks
        run: |
          ./gradlew generateCommonMainNinjaDatabaseSchema;
          ./gradlew verifySqlDelightMigration;
