name: PR Check
on:
  pull_request:
    branches: [ main ]

env:
  VERSION: ${{ vars.VERSION }}
  DESKTOP_VERSION: ${{ vars.DESKTOP_VERSION }}
  VERSION_CODE: ${{ vars.VERSION_CODE }}
  IS_DEBUG: ${{ vars.IS_DEBUG }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  SENTRY_ENVIRONMENT: ${{ vars.SENTRY_ENVIRONMENT }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

concurrency:
  group: pr-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-checks:
    runs-on: macos-latest
    environment: development
    steps:

      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run Spotless
        run: ./gradlew spotlessCheck

      - name: Run Lint
        run: ./gradlew lint

      - name: Run DB Checks
        run: |
          ./gradlew generateCommonMainNinjaDatabaseSchema;
          ./gradlew verifySqlDelightMigration;